name: this is me learning

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: printhello
        run: echo "hello world"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: printhello2
        run: echo "hello world again"

      - name: printhello3
        run: echo "hello world again and again"