name : howisthisworking 

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run : echo "this is hello world from job1 hahhahaha"

  test2:
    runs-on: ubuntu-24.04
    needs: test3
    steps:
      - run : echo "this is hello world from job2 hahahahhahahahahahahha"
    

  test3:
    runs-on: ubuntu-24.04
    steps:
      - run : echo "this is hello world from job3 hahhahaha"